# Generated by Django 2.0.2 on 2018-07-08 16:05
from django.db import migrations
from apichallenge.settings import BASE_DIR
import json
import os

def load_fixture(apps, schema_editor):
    """
    Load fixture data. If I were doing this my own way I would
    throw departures.json into a fixtures folder in the departures
    app and use python manage.py loaddata departures, or write a custom
    serializer like this to future-proof it from schema changes:
    https://stackoverflow.com/questions/25960850/loading-initial-data-with-django-1-7-and-data-migrations/39743581#39743581

    Anyway ... 
    """
    filename = os.path.join(BASE_DIR, 'departures.json')
    Departure = apps.get_model('departures', 'Departure')
    with open(filename) as f:
        json_data = json.loads(f.read())
        for departure in json_data:
            Departure.objects.create(
                name=departure['name'],
                start_date=departure['start_date'],
                finish_date=departure['finish_date'],
                category=departure['category']
            )

class Migration(migrations.Migration):
    dependencies = [
        ('departures', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
